version: "3.8"

services:
  mysql-db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234!qaAsql
      MYSQL_DATABASE: survey
      MYSQL_USER: semeru
      MYSQL_PASSWORD: 345semeru!

  backend:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    restart: always
    volumes:
      - .:/app/
    depends_on:
      - mysql-db
    working_dir: "/survey"
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
volumes:
  mysql_data: