# Generated by Django 4.0.6 on 2022-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_user_newuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='email',
        ),
        migrations.AddField(
            model_name='newuser',
            name='user_id',
            field=models.TextField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
